server:
  port: 9090

nacos:
  serverAddr: @nacos.serverAddr@
  namespace:
    gateway: @nacos.namespace.gateway@

app:
  id: @app.id@
apollo:
  meta: @apollo.meta@


authorization:
  url: @authorization.url@
