server:
  port: 8080

nacos:
  serverAddr: @nacos.serverAddr@
  namespace:
    gateway: @nacos.namespace.gateway@

app:
  id: @app.id@
apollo:
  meta: @apollo.meta@

management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
      path-mapping:
        metrics: _metrics
        prometheus: metrics
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: