server:
  port: 8080

nacos:
  serverAddr: @nacos.serverAddr@
  namespace:
    gateway: @nacos.namespace.gateway@

authority_management_system_url: @authorization.url@

app:
  id: @app.id@
apollo:
  meta: @apollo.meta@
  namespace:
    route-definition: @apollo.namespace.route-definition@
    breaker-config: @apollo.namespace.breaker-config@
    uri-role: @apollo.namespace.uri-role@

management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
      path-mapping:
        metrics: _metrics
        prometheus: metrics
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: